/***************************************************************
 *
 * Interactive LMC based on Swing
 * Copyright (c) 2007 Dr. Andrew Kwok-Fai LUI
 * The Open University of Hong Kong
 *
 * Enhance the learning effectiveness of students through greater interactions
 */
/*  This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package faifai.swinglmc;
import java.awt.Font;

public class OutputPanel extends javax.swing.JPanel {

  private Font font1 = new java.awt.Font("Courier New", 0, 10);
  private Font font2 = new java.awt.Font("Courier New", 0, 14);
  private Font font3 = new java.awt.Font("Courier New", Font.BOLD, 18);
    
  /** Creates new form OutputPanel */
  public OutputPanel() {
    initComponents();
  }
  
  public void update() {
    jTextArea1.setText(OutputBuffer.buffer.toString());
  }
  
  public void setFontSize(int size) {
    switch (size) {
        case 1:
            jTextArea1.setFont(font1); break;
        case 2:
            jTextArea1.setFont(font2); break;        
        case 3:
            jTextArea1.setFont(font3); break;           
    }
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();

    setLayout(new java.awt.GridLayout(1, 0));

    setBackground(new java.awt.Color(255, 255, 255));
    setFont(new java.awt.Font("Courier New", 0, 10));
    setMinimumSize(new java.awt.Dimension(120, 60));
    setPreferredSize(new java.awt.Dimension(120, 60));
    jTextArea1.setBackground(new java.awt.Color(255, 255, 204));
    jTextArea1.setColumns(20);
    jTextArea1.setEditable(false);
    jTextArea1.setFont(new java.awt.Font("Courier", 0, 11));
    jTextArea1.setRows(5);
    jTextArea1.setMargin(new java.awt.Insets(5, 5, 5, 5));
    jScrollPane1.setViewportView(jTextArea1);

    add(jScrollPane1);

  }// </editor-fold>//GEN-END:initComponents
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
  
}
